version: "3.1"

services:
  node:
    build: docker/node
    volumes:
      - .:/application
    ports:
      - "6001:6001"
    links:
      - redis

  beanstalkd:
    build: docker/beanstalkd

  redis:
    image: redis:6.0.1-alpine

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: deployer
      MYSQL_USER: deployer
      MYSQL_PASSWORD: secret
    volumes:
      - data:/var/lib/mysql

  nginx:
    build: docker/nginx
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - php
      - node

  queue:
    build: docker/artisan
    command: php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    links:
      - beanstalkd
      - mysql
      - redis

  broadcast:
    build: docker/artisan
    command: php artisan queue:work --queue=deployer-default --sleep=3 --tries=1
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    links:
      - beanstalkd
      - mysql
      - redis

  composer:
    build: docker/composer
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - .:/application
    links:
      - mysql

  php:
    build: docker/php
    volumes:
      - .:/application
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm.conf
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    links:
      - beanstalkd
      - mysql
      - redis

volumes:
  data:
    driver: local
